
iannotlist_file = ...
    joinpath(getenv('RS_TRUNK_DIR'), ...
        'cWorks', 'Project', 'MetabolomeGeneral', ...
        'CE-MS', 'AnnotationList', 'C_114_annotlist_160809-2_RSC1.csv');
annotlist_tbl = rsTable3('table');
annotlist_tbl.read_file(iannotlist_file, ...
    'sep', ',(?=(?:[^\"]*\"[^\"]*\")*(?![^\"]*\"))', ...
    'rowlabel_flag', false);

target_mzs = str2double(annotlist_tbl.get_colvec(4));
% target_mzs = 182.0482;

centroided_agilent_file = joinpath(getenv('RS_TMP_DIR'), ...
    'rs_MSpectra', '101-QCE-P-C-5_centroided_Agilent1_10.rsmspra');
centroided_file = joinpath(getenv('RS_PROJ_DIR'), ...
    'MasterHands', 'Examples', 'kiff_files1', ...
    '101-QCE-P-C-5_centroided1_7.rsmspra');
profile_file = joinpath(getenv('RS_PROJ_DIR'), ...
    'MasterHands', 'Examples', 'kiff_files1', ...
    '101-QCE-P-C-5.rsmspra');

[ mts_c_a, spectra_mzs_c_a, spectra_intsts_c_a ] = ...
    read_rsmspra_file1(centroided_agilent_file);
[ mts_c, spectra_mzs_c, spectra_intsts_c ] = ...
    read_rsmspra_file1(centroided_file);
% [ mts_p, spectra_mzs_p, spectra_intsts_p ] = ...
%     read_rsmspra_file1(profile_file);

%%

[ intsts_mat_c_a, closest_mzs_mat_c_a ] = ...
    get_ephes_from_rsmmsd_simple(target_mzs, ...
    spectra_mzs_c_a, spectra_intsts_c_a);

[ intsts_mat_c, closest_mzs_mat_c ] = ...
    get_ephes_from_rsmmsd_simple(target_mzs, ...
    spectra_mzs_c, spectra_intsts_c);

% [ intsts_mat_p, closest_mzs_mat_p ] = ...
%     get_ephes_from_rsmmsd_simple(target_mzs, ...
%     spectra_mzs_p, spectra_intsts_p);

plot(mts_c_a, intsts_mat_c_a(30,:));
figure;
plot(mts_c, intsts_mat_c(30,:));
