
ephemat_rs2dm_file = joinpath(getenv("RS_TMP_DIR"), 'rs_MSpectra', ...
    'testmspectrum_mini_ephemat.rs2dm');
[ ephemat_dat2d, ephemat_range_l_m, ephemat_range_l_n ] = ...
    read_rs2d_file1(ephemat_rs2dm_file, ...
        'range_l_m_var_type', 'double', ...
        'range_l_n_var_type', 'single', ...
        'val_var_type', 'int32');

matched_mz_mat_rs2dm_file = joinpath(getenv("RS_TMP_DIR"), 'rs_MSpectra', ...
    'testmspectrum_mini_matched_mz_mat.rs2dm');
[ matched_mz_mat_dat2d, matched_mz_mat_range_l_m, matched_mz_mat_range_l_n ] = ...
    read_rs2d_file1(matched_mz_mat_rs2dm_file, ...
        'range_l_m_var_type', 'double', ...
        'range_l_n_var_type', 'single', ...
        'val_var_type', 'double');


