
irsmspra_prof_file = joinpath(getenv('RS_PROJ_DIR'), ...
    'MasterHands', 'Examples', 'kiff_files1', ...
    '101-QCE-P-C-5.rsmspra');

irsmspra_cntr_mhands_file = joinpath(getenv('RS_PROJ_DIR'), ...
    'MasterHands', 'Examples', 'kiff_files1', ...
    '101-QCE-P-C-5_centroided1_7.rsmspra');   

irsmspra_prof_agilent_file = joinpath(getenv('RS_TMP_DIR'), ...
    'rs_MSpectra', ...
    '101-QCE-P-C-5_profile_Agilent1_6.rsmspra');  

irsmspra_cntr_agilent_file = joinpath(getenv('RS_TMP_DIR'), ...
    'rs_MSpectra', ...
    '101-QCE-P-C-5_centroided_Agilent1_6.rsmspra');  

 [ mts_prof, spectra_mzs_prof, spectra_intsts_prof ] ...
    = read_rsmspra_file1(irsmspra_prof_file);

 [ mts_cntr_mhands, spectra_mzs_cntr_mhands, spectra_intsts_cntr_mhands ] ...
    = read_rsmspra_file1(irsmspra_cntr_mhands_file);

 [ mts_prof_agilent, spectra_mzs_prof_agilent, spectra_intsts_prof_agilent ] ...
    = read_rsmspra_file1(irsmspra_prof_agilent_file);

 [ mts_cntr_agilent, spectra_mzs_cntr_agilent, spectra_intsts_cntr_agilent ] ...
    = read_rsmspra_file1(irsmspra_cntr_agilent_file);

peakinfo_file = ...
    joinpath(getenv('RS_PROJ_DIR'), ...
        'MasterHands', 'Examples', 'kiff_files1', ...
        'QCsample_101-QCE-P-C-5_peakinfo1_7.tsv');

peakinfo_tbl = rsTable3('matrix');
peakinfo_tbl.read_file(peakinfo_file, ...
    'rowlabel_flag', true);

%% 

metab_idx = 8;
metab_rowlabel = peakinfo_tbl.rowlabels{ metab_idx };
colnam_to_val_h = ...
    peakinfo_tbl.get_rowvec_hash(metab_rowlabel);
peak_MT_top = colnam_to_val_h("Peak MT top");
peak_mz     = colnam_to_val_h("Peak m/z");

[ peak_MT_top_cntr_mhands, peak_MT_cntr_mhands_idx ] = ...
    closest_value_in_sorted(mts_cntr_mhands, peak_MT_top);
[ peak_mz_top_cntr_mhands, peak_mz_cntr_mhands_idx ] = ...
    closest_value_in_sorted(spectra_mzs_cntr_mhands{ peak_MT_cntr_mhands_idx }, ...
                            peak_mz);
peak_intst_top_cntr_mhands = ...
    spectra_intsts_cntr_mhands{ peak_MT_cntr_mhands_idx }(peak_mz_cntr_mhands_idx);


[ peak_MT_top_cntr_agilent, peak_MT_cntr_agilent_idx ] = ...
    closest_value_in_sorted(mts_cntr_agilent, peak_MT_top);
[ peak_mz_top_cntr_agilent, peak_mz_cntr_agilent_idx ] = ...
    closest_value_in_sorted(spectra_mzs_cntr_agilent{ peak_MT_cntr_agilent_idx }, ...
                            peak_mz);
peak_intst_top_cntr_agilent = ...
    spectra_intsts_cntr_agilent{ peak_MT_cntr_agilent_idx }(peak_mz_cntr_agilent_idx);



%%

[ peak_MT_top_prof, peak_MT_prof_idx ] = ...
    closest_value_in_sorted(mts_prof, peak_MT_top_cntr_mhands);
[ peak_mz_top_prof, peak_mz_prof_idx ] = ...
    closest_value_in_sorted(spectra_mzs_prof{ peak_MT_prof_idx }, ...
                            peak_mz);

prof_mz_range_lo_idx = max([ peak_mz_prof_idx - 10, 1 ]);
prof_mz_range_hi_idx = min([ peak_mz_prof_idx + 10, length(spectra_mzs_prof{ peak_MT_prof_idx }) ]);

plot(spectra_mzs_prof{ peak_MT_prof_idx }(prof_mz_range_lo_idx:prof_mz_range_hi_idx), ...
     spectra_intsts_prof{ peak_MT_prof_idx }(prof_mz_range_lo_idx:prof_mz_range_hi_idx));

%%

hold on;
scatter(peak_mz_top_cntr_mhands, peak_intst_top_cntr_mhands);
hold on;
scatter(peak_mz_top_cntr_agilent, peak_intst_top_cntr_agilent);
hold off;

legend('Spectrum', 'MH peak', 'Agilent peak');

%%

[ ephe_cntr_mhands_intsts, ephe_cntr_mhands_closest_mzs ] = ...
    get_ephe_from_rsmmsd_simple(peak_mz, ...
        spectra_mzs_cntr_mhands, ...
        spectra_intsts_cntr_mhands);

[ ephe_cntr_agilent_intsts, ephe_cntr_agilent_closest_mzs ] = ...
    get_ephe_from_rsmmsd_simple(peak_mz, ...
        spectra_mzs_cntr_agilent, ...
        spectra_intsts_cntr_agilent);



figure;
plot(mts_cntr_mhands, ephe_cntr_mhands_intsts);

figure;
plot(mts_cntr_agilent, ephe_cntr_agilent_intsts);

%%
figure;
plot(spectra_mzs_prof_agilent{peak_MT_prof_idx}, spectra_intsts_prof_agilent{peak_MT_prof_idx})
plot(spectra_mzs_prof_agilent{peak_MT_prof_idx}(2857:2877), spectra_intsts_prof_agilent{peak_MT_prof_idx}(2857:2877))
